package com.api.market.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.math.BigDecimal;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="Product")
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class Product {
    @DynamoDBHashKey
    @Id
    @DynamoDBAutoGeneratedKey
    @JsonIgnore
    private Integer id;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String type;
    @DynamoDBAttribute
    private BigDecimal price;
}
